import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms'; // additional imports based on need

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { TablerefreshComponent } from './tablerefresh/tablerefresh.component'; // generated by generate component

@NgModule({
  declarations: [
    AppComponent,
    TablerefreshComponent // generated by generate component
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    FormsModule // need to manually add to import once imported above
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
